### ISSUE TITLE
Error -6 when calling clCreateCommandQueueWithProperties

### ISSUE THREAD

**Issue by joshgrobin** [Bendr0id/wolf-multi-miner#1]
Whenever I try to run the miner I get "Error -6 when calling clCreateCommandQueueWithProperties" for each Graphics card. It also says that my wallet is invalid even though I know for a fact that it is valid. After that the program doesn't seem to do anything until I control Z out of it. I am running 2 cards and they are both AMD R7s. The miner was compiled in Ubuntu 16.04.3 with  AMDAPPSDK-3.0 and amdgpu-pro-17.40-492261 installed.

**Comment by Bendr0id** [comment]
Sorry @joshgrobin i never used amd/cuda stuff. It was just already implemented into wolfs miner. I just modified the cpu code. Maybe you should better ask for help in wolf-xmr-miner repo.

**Comment by joshgrobin** [comment]
Thank you for the reply. As for it saying invalid wallet, that was because I was solo mining using "daemon+tcp://" that does not appear to work with AEON. I just removed the "daemon+tcp://" and just left the address and port number in there instead and that appears to work for getting rid of the wallet message.
